### ISSUE TITLE
Create labels

### ISSUE THREAD

**Issue by yusufyilmazf** [octoposprime/op-em-solid#2]
Please create appropriate tags for the "op-em-solid" repository and add them to the discussion with colors and descriptions.
https://github.com/orgs/octoposprime/discussions/14

**Comment by yavuz-yusuf** [comment]
Here is Labels for op-em-solid Repository
CAD: Computer Aided Design (#1B4F72)

3D Modeling: Mathematical coordinate-based design of an object in three dimensions (#F39C12)

2D Modeling: Mathematical coordinate-based design of an object in two dimensions (#52BE80)

Part Design: design of a part of a main object (#34495E)

Mold Design: Creating the mold that will be used to shape a desired product.(#17202A)

Simulation:- Testing and analyzing a design virtually (#CB4335)

aesthetic: Visual appeal and pleasing appearance of a design. (#94CB35)

interference: The process of checking for overlapping parts in a CAD assembly (#5C35CB)

assembly: process of putting together different parts to create a whole functional product. (#CB3550)

scaling: resizing an object proportionally in software. (#00BA6B)

Exploded : breaking down a complex object into its individual components. (#922B21)
